export function createFanhaoDependencies(deps) {
  if (!deps.diskUsage || typeof deps.diskUsage !== "object") {
    throw new TypeError("Missing FanHao dependency: diskUsage");
  }
  return {
    diskUsage: deps.diskUsage,
    catalog: pick(deps, ["codePrefixService", "notFound", "rankingService", "sendJson", "studioService"]),
    library: pick(deps, [
      "appConfigService",
      "getLastScanError",
      "getLibrary",
      "peopleScopeService",
      "personListService",
      "peoplePayloadStamp",
      "publicPerson",
      "refreshLibrary",
      "requestAccess",
      "requireLocalAdmin",
      "sendJson",
      "userStateSummary"
    ]),
    settings: pick(deps, ["appConfigService"]),
    userState: pick(deps, [
      "clampInteger",
      "favoriteStateService",
      "filterWorkList",
      "getLibrary",
      "maxWorkLimit",
      "notFound",
      "playbackProgressService",
      "prewarmCoreWorkCovers",
      "prewarmRemoteImagesForWorks",
      "prewarmVideoProbesForWorks",
      "prewarmWorkInfoDetails",
      "publicWork",
      "readJsonBody",
      "recentWatchedDays",
      "resolvePlayableVideoFile",
      "sendJson",
      "sortWorkList",
      "userStateStamp",
      "workFacets",
      "workQueryStamp"
    ]),
    works: pick(deps, [
      "actorMovieInfoStamp",
      "adminCoreMutationService",
      "actorMovieStamp",
      "actorProfileMergeCandidates",
      "actorProfilePublicationLifecycleService",
      "actorProfileRow",
      "actorMissingSearchWorks",
      "actorMissingSearchWorksForPeople",
      "clampInteger",
      "coreLocalWorkIdsForPeople",
      "coreMissingWorksForPerson",
      "corePersonFallbackRecord",
      "defaultWorkLimit",
      "dedupeWorksForDisplay",
      "displayWorkTitle",
      "enrichLocalWorksWithActorMovieIndex",
      "enrichLocalWorksWithActorMovieInfo",
      "fastMissingCodeSearch",
      "favoriteStateService",
      "galleryMediaService",
      "generateWorkCover",
      "getLibrary",
      "hydrateMissingSearchWorks",
      "isVrWork",
      "createWorkSearchMatcher",
      "localSearchWorkByCodeKey",
      "localWorksByCodePrefix",
      "maxActorAvatarBytes",
      "maxWorkLimit",
      "manualCoverStateService",
      "mediaResponseService",
      "mediaStreamService",
      "mergedActorMovieRows",
      "mergedPersonMembers",
      "mergedPersonRecord",
      "missingActorWorksForPerson",
      "notFound",
      "peoplePayloadStamp",
      "peopleScopeService",
      "playbackProgressService",
      "prewarmPersonMerge",
      "prewarmCoreWorkCovers",
      "prewarmLocalWorkCodeKeys",
      "prewarmWorkSearch",
      "prewarmWorkInfoDetails",
      "prewarmRemoteImagesForWorks",
      "prewarmVideoProbesForWorks",
      "publicActorProfile",
      "publicPerson",
      "publicWork",
      "publicWorkAvailability",
      "rankingMissingSearchWorks",
      "readJsonBody",
      "requireLocalAdmin",
      "requireTrustedFileMutation",
      "resolveLibraryPersonByPublicId",
      "resolveLibraryWorkByPublicId",
      "resolveVideoFileByPublicId",
      "searchPeople",
      "sendJson",
      "storedWorkCodeKey",
      "userStateStamp",
      "videoProbeService",
      "workCodeKeySetForWorks",
      "workHasCoreCover",
      "workHasLocalMarker",
      "workInfoFacetRow",
      "workInfoRow",
      "workClassificationService",
      "workLocalMutationService",
      "workMoveJobService",
      "workQueryStamp"
    ])
  };
}

function pick(source, keys) {
  return Object.fromEntries(keys.map((key) => {
    if (source[key] === undefined) throw new TypeError(`Missing FanHao dependency: ${key}`);
    return [key, source[key]];
  }));
}
