import fs from "node:fs";
import fsp from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { chromium } from "playwright-core";

function parseArgs(argv) {
  const options = { out: "", profileDir: "", timeoutSeconds: 300 };
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    const value = () => argv[++index] || "";
    if (arg === "--out") options.out = value();
    else if (arg === "--profile-dir") options.profileDir = value();
    else if (arg === "--timeout-seconds") options.timeoutSeconds = Math.max(30, Number(value()) || 300);
    else if (arg === "--help" || arg === "-h") options.help = true;
  }
  return options;
}

function browserPath() {
  const candidates = [
    "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe",
    "C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe",
    "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",
    "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
  ];
  const executable = candidates.find((candidate) => fs.existsSync(candidate));
  if (!executable) throw new Error("未找到 Microsoft Edge 或 Google Chrome");
  return executable;
}

function hasLoginCookie(cookies) {
  const names = new Set(cookies.map((cookie) => cookie.name));
  return ["sessionid", "sessionid_ss", "sid_guard", "sid_tt"].some((name) => names.has(name));
}

function netscapeText(cookies) {
  const lines = ["# Netscape HTTP Cookie File", "# Generated by Douyin Download Manager", ""];
  for (const cookie of cookies) {
    if (!cookie.name || !String(cookie.domain || "").includes("douyin")) continue;
    const rawDomain = String(cookie.domain || ".douyin.com");
    const includeSubdomains = rawDomain.startsWith(".") ? "TRUE" : "FALSE";
    const domain = cookie.httpOnly ? `#HttpOnly_${rawDomain}` : rawDomain;
    const secure = cookie.secure ? "TRUE" : "FALSE";
    const expires = Number.isFinite(cookie.expires) && cookie.expires > 0 ? Math.floor(cookie.expires) : 0;
    const value = String(cookie.value || "").replace(/[\r\n\t]/g, "");
    lines.push([domain, includeSubdomains, cookie.path || "/", secure, expires, cookie.name, value].join("\t"));
  }
  return `${lines.join("\n")}\n`;
}

async function saveCookies(outPath, cookies) {
  await fsp.mkdir(path.dirname(outPath), { recursive: true });
  const temporary = `${outPath}.${process.pid}.tmp`;
  await fsp.writeFile(temporary, netscapeText(cookies), "utf8");
  await fsp.rm(outPath, { force: true });
  await fsp.rename(temporary, outPath);
}

async function main() {
  const options = parseArgs(process.argv.slice(2));
  if (options.help) {
    console.log("cookie-login.mjs --out <cookies.txt> --profile-dir <dir> [--timeout-seconds 300]");
    return;
  }
  if (!options.out || !options.profileDir) throw new Error("缺少 --out 或 --profile-dir");

  await fsp.mkdir(options.profileDir, { recursive: true });
  const context = await chromium.launchPersistentContext(options.profileDir, {
    executablePath: browserPath(),
    headless: false,
    viewport: null,
    args: ["--disable-blink-features=AutomationControlled", "--no-first-run"],
  });

  try {
    await context.clearCookies();
    const pages = context.pages();
    const page = pages[0] || (await context.newPage());
    await page.goto("https://www.douyin.com/", { waitUntil: "domcontentloaded", timeout: 60000 });
    console.log("请在 Edge 中登录抖音；检测到登录成功后会自动保存并关闭窗口。");

    const deadline = Date.now() + options.timeoutSeconds * 1000;
    while (Date.now() < deadline) {
      if (!context.pages().length) throw new Error("登录窗口已关闭");
      const cookies = await context.cookies(["https://www.douyin.com/"]);
      if (hasLoginCookie(cookies)) {
        await page.waitForTimeout(1200);
        const finalCookies = await context.cookies(["https://www.douyin.com/"]);
        await saveCookies(path.resolve(options.out), finalCookies);
        console.log(`登录成功，已保存 ${finalCookies.length} 项 Cookie。`);
        return;
      }
      await page.waitForTimeout(1000);
    }
    throw new Error("等待登录超时，请重新点击登录");
  } finally {
    await context.close().catch(() => {});
  }
}

main().catch((error) => {
  console.error(error?.message || String(error));
  process.exitCode = 1;
});
